namespace EndTime.Core;

/// <summary>
/// A convenience enum for referencing CP437 characters with friendlyish names.
/// 
/// This was AI generated -- turns out it is good for something?
/// </summary>
public enum CodePage437 : byte
{
    // 0x00 - 0x1F: Control Characters / Dingbats
    Null = 0x00,
    SmileyWhite = 0x01,
    SmileyBlack = 0x02,
    Heart = 0x03,
    Diamond = 0x04,
    Club = 0x05,
    Spade = 0x06,
    Bullet = 0x07,
    InverseBullet = 0x08,
    CircleWhite = 0x09,
    InverseCircleWhite = 0x0A,
    MaleSign = 0x0B,
    FemaleSign = 0x0C,
    MusicalNoteSingle = 0x0D,
    MusicalNoteDouble = 0x0E,
    Sun = 0x0F,
    PointerRightFilled = 0x10,
    PointerLeftFilled = 0x11,
    ArrowUpDown = 0x12,
    ExclamationDouble = 0x13,
    Pilcrow = 0x14,
    SectionSign = 0x15,
    RectangleHorizontalFilled = 0x16,
    ArrowUpDownUnderlined = 0x17,
    ArrowUp = 0x18,
    ArrowDown = 0x19,
    ArrowRight = 0x1A,
    ArrowLeft = 0x1B,
    RightAngle = 0x1C,
    ArrowLeftRight = 0x1D,
    ArrowUpFilled = 0x1E,
    ArrowDownFilled = 0x1F,

    // 0x20 - 0x7E: Standard ASCII
    Space = 0x20,
    ExclamationMark = 0x21,
    QuotationMark = 0x22,
    NumberSign = 0x23,
    DollarSign = 0x24,
    PercentSign = 0x25,
    Ampersand = 0x26,
    Apostrophe = 0x27,
    ParenthesisLeft = 0x28,
    ParenthesisRight = 0x29,
    Asterisk = 0x2A,
    PlusSign = 0x2B,
    Comma = 0x2C,
    HyphenMinus = 0x2D,
    FullStop = 0x2E,
    Solidus = 0x2F,
    Digit0 = 0x30, Digit1 = 0x31, Digit2 = 0x32, Digit3 = 0x33, Digit4 = 0x34,
    Digit5 = 0x35, Digit6 = 0x36, Digit7 = 0x37, Digit8 = 0x38, Digit9 = 0x39,
    Colon = 0x3A,
    Semicolon = 0x3B,
    LessThanSign = 0x3C,
    EqualsSign = 0x3D,
    GreaterThanSign = 0x3E,
    QuestionMark = 0x3F,
    CommercialAt = 0x40,
    UpperA = 0x41, UpperB = 0x42, UpperC = 0x43, UpperD = 0x44, UpperE = 0x45,
    UpperF = 0x46, UpperG = 0x47, UpperH = 0x48, UpperI = 0x49, UpperJ = 0x4A,
    UpperK = 0x4B, UpperL = 0x4C, UpperM = 0x4D, UpperN = 0x4E, UpperO = 0x4F,
    UpperP = 0x50, UpperQ = 0x51, UpperR = 0x52, UpperS = 0x53, UpperT = 0x54,
    UpperU = 0x55, UpperV = 0x56, UpperW = 0x57, UpperX = 0x58, UpperY = 0x59,
    UpperZ = 0x5A,
    BracketLeft = 0x5B,
    ReverseSolidus = 0x5C,
    BracketRight = 0x5D,
    CircumflexAccent = 0x5E,
    LowLine = 0x5F,
    GraveAccent = 0x60,
    LowerA = 0x61, LowerB = 0x62, LowerC = 0x63, LowerD = 0x64, LowerE = 0x65,
    LowerF = 0x66, LowerG = 0x67, LowerH = 0x68, LowerI = 0x69, LowerJ = 0x6A,
    LowerK = 0x6B, LowerL = 0x6C, LowerM = 0x6D, LowerN = 0x6E, LowerO = 0x6F,
    LowerP = 0x70, LowerQ = 0x71, LowerR = 0x72, LowerS = 0x73, LowerT = 0x74,
    LowerU = 0x75, LowerV = 0x76, LowerW = 0x77, LowerX = 0x78, LowerY = 0x79,
    LowerZ = 0x7A,
    BraceLeft = 0x7B,
    VerticalLine = 0x7C,
    BraceRight = 0x7D,
    Tilde = 0x7E,
    House = 0x7F, // DEL replacement

    // 0x80 - 0xAF: Extended Latin / Currency
    CapitalC_Cedilla = 0x80,
    SmallU_Diaeresis = 0x81,
    SmallE_Acute = 0x82,
    SmallA_Circumflex = 0x83,
    SmallA_Diaeresis = 0x84,
    SmallA_Grave = 0x85,
    SmallA_RingAbove = 0x86,
    SmallC_Cedilla = 0x87,
    SmallE_Circumflex = 0x88,
    SmallE_Diaeresis = 0x89,
    SmallE_Grave = 0x8A,
    SmallI_Diaeresis = 0x8B,
    SmallI_Circumflex = 0x8C,
    SmallI_Grave = 0x8D,
    CapitalA_Diaeresis = 0x8E,
    CapitalA_RingAbove = 0x8F,
    CapitalE_Acute = 0x90,
    SmallAe = 0x91,
    CapitalAe = 0x92,
    SmallO_Circumflex = 0x93,
    SmallO_Diaeresis = 0x94,
    SmallO_Grave = 0x95,
    SmallU_Circumflex = 0x96,
    SmallU_Grave = 0x97,
    SmallY_Diaeresis = 0x98,
    CapitalO_Diaeresis = 0x99,
    CapitalU_Diaeresis = 0x9A,
    CentSign = 0x9B,
    PoundSign = 0x9C,
    YenSign = 0x9D,
    PesetaSign = 0x9E,
    FlorinSign = 0x9F,
    SmallA_Acute = 0xA0,
    SmallI_Acute = 0xA1,
    SmallO_Acute = 0xA2,
    SmallU_Acute = 0xA3,
    SmallN_Tilde = 0xA4,
    CapitalN_Tilde = 0xA5,
    FeminineOrdinal = 0xA6,
    MasculineOrdinal = 0xA7,
    InvertedQuestionMark = 0xA8,
    ReversedNotSign = 0xA9,
    NotSign = 0xAA,
    OneHalf = 0xAB,
    OneQuarter = 0xAC,
    InvertedExclamationMark = 0xAD,
    AngleBracketLeft = 0xAE,
    AngleBracketRight = 0xAF,

    // 0xB0 - 0xDF: Box Drawing & Blocks
    LightShade = 0xB0,
    MediumShade = 0xB1,
    DarkShade = 0xB2,
    BoxVertical = 0xB3,
    BoxVerticalLeft = 0xB4,
    BoxVerticalDoubleLeftSingle = 0xB5,
    BoxVerticalSingleLeftDouble = 0xB6,
    BoxDownDoubleLeftSingle = 0xB7,
    BoxDownSingleLeftDouble = 0xB8,
    BoxVerticalDoubleLeftDouble = 0xB9,
    BoxVerticalDouble = 0xBA,
    BoxDownDoubleLeftDouble = 0xBB,
    BoxUpDoubleLeftDouble = 0xBC,
    BoxUpDoubleLeftSingle = 0xBD,
    BoxUpSingleLeftDouble = 0xBE,
    BoxDownSingleLeftSingle = 0xBF,
    BoxUpSingleRightSingle = 0xC0,
    BoxUpSingleHorizontalSingle = 0xC1,
    BoxDownSingleHorizontalSingle = 0xC2,
    BoxVerticalSingleRightSingle = 0xC3,
    BoxHorizontalSingle = 0xC4,
    BoxVerticalSingleHorizontalSingle = 0xC5,
    BoxVerticalSingleRightDouble = 0xC6,
    BoxVerticalDoubleRightSingle = 0xC7,
    BoxUpDoubleRightDouble = 0xC8,
    BoxUpDoubleHorizontalDouble = 0xC9, // Mislabelled in some tables as Down
    BoxDownDoubleHorizontalDouble = 0xCA,
    BoxVerticalDoubleRightDouble = 0xCB,
    BoxHorizontalDouble = 0xCC,
    BoxVerticalDoubleHorizontalDouble = 0xCD,
    BoxHorizontalSingleUpDouble = 0xCE,
    BoxHorizontalSingleDownDouble = 0xCF,
    BoxHorizontalDoubleUpSingle = 0xD0,
    BoxHorizontalDoubleDownSingle = 0xD1,
    BoxUpDoubleHorizontalSingle = 0xD2,
    BoxDownDoubleHorizontalSingle = 0xD3,
    BoxUpSingleRightDouble = 0xD4,
    BoxDownSingleRightDouble = 0xD5,
    BoxVerticalDoubleHorizontalSingle = 0xD6,
    BoxVerticalSingleHorizontalDouble = 0xD7,
    BoxUpDoubleRightSingle = 0xD8,
    BoxDownSingleLeftSingle2 = 0xD9, // Corner
    BoxDownSingleRightSingle2 = 0xDA, // Corner
    FullBlock = 0xDB,
    LowerHalfBlock = 0xDC,
    LeftHalfBlock = 0xDD,
    RightHalfBlock = 0xDE,
    UpperHalfBlock = 0xDF,

    // 0xE0 - 0xFF: Greek & Math
    GreekAlpha = 0xE0,
    GreekBeta = 0xE1, // Also German sharp S
    GreekGamma = 0xE2,
    GreekPi = 0xE3,
    GreekSigmaUpper = 0xE4,
    GreekSigmaLower = 0xE5,
    GreekMu = 0xE6,
    GreekTau = 0xE7,
    GreekPhiUpper = 0xE8,
    GreekTheta = 0xE9,
    GreekOmega = 0xEA,
    GreekDelta = 0xEB,
    Infinity = 0xEC,
    GreekPhiLower = 0xED,
    GreekEpsilon = 0xEE,
    Intersection = 0xEF,
    IdenticalTo = 0xF0,
    PlusMinus = 0xF1,
    GreaterOrEqual = 0xF2,
    LessOrEqual = 0xF3,
    IntegralUpper = 0xF4,
    IntegralLower = 0xF5,
    DivisionSign = 0xF6,
    AlmostEqual = 0xF7,
    DegreeSign = 0xF8,
    BulletSmall = 0xF9,
    MiddleDot = 0xFA,
    SquareRoot = 0xFB,
    SuperscriptN = 0xFC,
    SuperscriptTwo = 0xFD,
    BlackSquare = 0xFE,
    NonBreakingSpace = 0xFF
}
